/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.City;
import model.Encounter;
import model.EncounterHistory;
import model.PatientDirectory;
import model.VitalSigns;

/**
 *
 * @author deepalikasture
 */
public class AddEncounterHistory extends javax.swing.JPanel {

    /**
     * Creates new form AddEncounterHistory
     */
    
     PatientDirectory history;
    City city;
    public AddEncounterHistory(PatientDirectory history,City city) {
        initComponents();
        
        this.history = history;
        this.city=city;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRespiratoryRate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHR = new javax.swing.JTextField();
        Weigh = new javax.swing.JLabel();
        Weight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        lblRespiratory = new javax.swing.JLabel();
        lblHR = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Add Patient Vital signs");

        jLabel6.setText("Respiratory");

        txtRespiratoryRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRespiratoryRateKeyReleased(evt);
            }
        });

        jLabel7.setText("Heart Rate");

        txtHR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHRKeyReleased(evt);
            }
        });

        Weigh.setText("Weight");

        Weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WeightKeyReleased(evt);
            }
        });

        jLabel9.setText("Blood Pressure");

        txtBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBPKeyReleased(evt);
            }
        });

        jLabel10.setText("Temperature");

        txtTemperature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTemperatureKeyReleased(evt);
            }
        });

        jButton1.setText("Add Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Patient ID");

        txtPatientID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatientIDKeyReleased(evt);
            }
        });

        lblRespiratory.setForeground(new java.awt.Color(255, 0, 0));

        lblHR.setForeground(new java.awt.Color(204, 0, 0));

        lblWeight.setForeground(new java.awt.Color(255, 0, 51));

        lblTemp.setForeground(new java.awt.Color(255, 0, 51));

        lblID.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Weigh)
                                .addComponent(jLabel7)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(119, 119, 119)
                                .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRespiratory)
                            .addComponent(lblHR)
                            .addComponent(lblWeight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBP)
                    .addComponent(lblTemp)
                    .addComponent(lblID))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespiratory)
                    .addComponent(lblBP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHR)
                    .addComponent(lblTemp))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Weigh)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblWeight))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(lblID))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Integer id = Integer.parseInt(txtPatientID.getText());
         
        Integer bp = Integer.parseInt(txtBP.getText());
      Integer pulse = Integer.parseInt(txtHR.getText());
      Integer bt = Integer.parseInt(txtTemperature.getText());
      Integer respiration = Integer.parseInt(txtRespiratoryRate.getText());
      Integer weight = Integer.parseInt(txtRespiratoryRate.getText());
    String timestamp = new SimpleDateFormat("MM/dd/yyyy").format(Calendar.getInstance().getTime());

  

for(int i=0; i<history.getPatientList().size(); i++)
{
   int patientid = (history.getPatientList().get(i).getPatientID());
    if(id == patientid)
    {
      EncounterHistory eh=history.getPatientList().get(i).getEncounterHistory();
    VitalSigns signs = new VitalSigns( pulse,bp,weight,respiration,bt);
      Encounter encounter=new Encounter(signs,"01/01/2020");
       eh.addNewEncounter(encounter);
        
    

JOptionPane.showMessageDialog(this,"New vitals added for the patient.");
      
     
      txtPatientID.setText("");
      txtBP.setText("");
      txtHR.setText("");
      txtBP.setText("");
      txtRespiratoryRate.setText("");
      Weight.setText("");
}  
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRespiratoryRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespiratoryRateKeyReleased
        // TODO add your handling code here:
        
         String check=txtRespiratoryRate.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");

        Matcher matchPattern=pattern.matcher(check);
            if(!matchPattern.matches())
            {
                lblRespiratory.setText("Please Enter Valid number." );
            
            }
            else{
                lblRespiratory.setText(null);
            }
    }//GEN-LAST:event_txtRespiratoryRateKeyReleased

    private void txtHRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHRKeyReleased
        // TODO add your handling code here:
        
        String check=txtHR.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");

        Matcher matchPattern=pattern.matcher(check);
            if(!matchPattern.matches())
            {
                lblHR.setText("Please Enter Valid number." );
            
            }
            else{
                lblHR.setText(null);
            }
        
    }//GEN-LAST:event_txtHRKeyReleased

    private void WeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WeightKeyReleased
        // TODO add your handling code here:
        
        String check=Weight.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");

        Matcher matchPattern=pattern.matcher(check);
            if(!matchPattern.matches())
            {
                lblWeight.setText("Please Enter Valid number." );
            
            }
            else{
                lblWeight.setText(null);
            }
        
    }//GEN-LAST:event_WeightKeyReleased

    private void txtBPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBPKeyReleased
        // TODO add your handling code here:
        
        String check=txtBP.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");

        Matcher matchPattern=pattern.matcher(check);
            if(!matchPattern.matches())
            {
                lblBP.setText("Please Enter Valid number." );
            
            }
            else{
                lblBP.setText(null);
            }
    }//GEN-LAST:event_txtBPKeyReleased

    private void txtTemperatureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemperatureKeyReleased
        // TODO add your handling code here:
        
         String check=txtTemperature.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");

        Matcher matchPattern=pattern.matcher(check);
            if(!matchPattern.matches())
            {
                lblTemp.setText("Please Enter Valid number." );
            
            }
            else{
                lblTemp.setText(null);
            }
    }//GEN-LAST:event_txtTemperatureKeyReleased

    private void txtPatientIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientIDKeyReleased
        // TODO add your handling code here:
         String check=txtPatientID.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");

        Matcher matchPattern=pattern.matcher(check);
            if(!matchPattern.matches())
            {
                lblID.setText("Please Enter Valid number." );
            
            }
            else{
                lblID.setText(null);
            }
    }//GEN-LAST:event_txtPatientIDKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Weigh;
    private javax.swing.JTextField Weight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblHR;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblRespiratory;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtHR;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
