/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author deepalikasture
 * Assignment 1
 * Create and View PERSON Profile
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Person person;
    
    public CreateJPanel(Person person) {
        initComponents();
        
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGeographicData = new javax.swing.JLabel();
        txtGeographicData = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblTelephoneNumber = new javax.swing.JLabel();
        txtTelephoneNumber = new javax.swing.JTextField();
        lblFaxNumber = new javax.swing.JLabel();
        txtFaxNumber = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        lblSocialSecurityNumber = new javax.swing.JLabel();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        lblDeviceID = new javax.swing.JLabel();
        txtDeviceID = new javax.swing.JTextField();
        lblLinkedIn = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        lblIPAdress = new javax.swing.JLabel();
        txtIPAdress = new javax.swing.JTextField();
        lblHealthPlanBeneficiaryNumber = new javax.swing.JLabel();
        txtHealthPlanBeneficiaryNumber = new javax.swing.JTextField();
        lblGeographicData1 = new javax.swing.JLabel();
        txtBankAccountNumber = new javax.swing.JTextField();
        lblCertificatelicensenumber = new javax.swing.JLabel();
        txtCertificateLicenseNumber = new javax.swing.JTextField();
        lblVehicleIdentifier = new javax.swing.JLabel();
        txtVehicleIdentifier = new javax.swing.JTextField();
        lblUniqueID = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtDOB = new com.toedter.calendar.JDateChooser();
        btnUpload = new javax.swing.JButton();
        txtUniqueID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblValName = new javax.swing.JLabel();
        lblValVeh = new javax.swing.JLabel();
        lblValDevNum = new javax.swing.JLabel();
        lblValLinkedIn = new javax.swing.JLabel();
        lblValIpAdd = new javax.swing.JLabel();
        lblValUniqueId = new javax.swing.JLabel();
        lblValMed = new javax.swing.JLabel();
        lblValSSN = new javax.swing.JLabel();
        lblValHealth = new javax.swing.JLabel();
        lblValBankAcc = new javax.swing.JLabel();
        lblValLic = new javax.swing.JLabel();
        lblValGeo = new javax.swing.JLabel();
        lblValTel = new javax.swing.JLabel();
        lblValFax = new javax.swing.JLabel();
        lblValEmail = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Person");

        lblName.setText("Name");

        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        lblGeographicData.setText("Geographic Data");

        txtGeographicData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGeographicDataFocusLost(evt);
            }
        });
        txtGeographicData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGeographicDataKeyReleased(evt);
            }
        });

        lblDOB.setText("Date of Birth");

        lblTelephoneNumber.setText("Telephone Number");

        txtTelephoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelephoneNumberFocusLost(evt);
            }
        });
        txtTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumberActionPerformed(evt);
            }
        });
        txtTelephoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephoneNumberKeyReleased(evt);
            }
        });

        lblFaxNumber.setText("Fax Number");

        txtFaxNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFaxNumberFocusLost(evt);
            }
        });
        txtFaxNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumberActionPerformed(evt);
            }
        });
        txtFaxNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxNumberKeyReleased(evt);
            }
        });

        lblEmail.setText("Email Address");

        txtEmailAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailAddressFocusLost(evt);
            }
        });
        txtEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyReleased(evt);
            }
        });

        lblSocialSecurityNumber.setText("Social Security number");

        txtSocialSecurityNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSocialSecurityNumberFocusLost(evt);
            }
        });
        txtSocialSecurityNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSocialSecurityNumberKeyReleased(evt);
            }
        });

        lblMedicalRecordNumber.setText("Medical Record Number");

        txtMedicalRecordNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMedicalRecordNumberFocusLost(evt);
            }
        });
        txtMedicalRecordNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicalRecordNumberKeyReleased(evt);
            }
        });

        lblDeviceID.setText("Device Number");

        txtDeviceID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeviceIDFocusLost(evt);
            }
        });
        txtDeviceID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDeviceIDKeyReleased(evt);
            }
        });

        lblLinkedIn.setText("LinkedIn ID");

        txtLinkedIn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLinkedInFocusLost(evt);
            }
        });
        txtLinkedIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLinkedInKeyReleased(evt);
            }
        });

        lblIPAdress.setText("IP Address");

        txtIPAdress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIPAdressFocusLost(evt);
            }
        });
        txtIPAdress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIPAdressKeyReleased(evt);
            }
        });

        lblHealthPlanBeneficiaryNumber.setText("Health Plan beneficiary number");

        txtHealthPlanBeneficiaryNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHealthPlanBeneficiaryNumberFocusLost(evt);
            }
        });
        txtHealthPlanBeneficiaryNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHealthPlanBeneficiaryNumberKeyReleased(evt);
            }
        });

        lblGeographicData1.setText("Bank Account Number");

        txtBankAccountNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBankAccountNumberFocusLost(evt);
            }
        });
        txtBankAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankAccountNumberKeyReleased(evt);
            }
        });

        lblCertificatelicensenumber.setText("Certificate/License Number");

        txtCertificateLicenseNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCertificateLicenseNumberFocusLost(evt);
            }
        });
        txtCertificateLicenseNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCertificateLicenseNumberKeyReleased(evt);
            }
        });

        lblVehicleIdentifier.setText("Vehicle Number");

        txtVehicleIdentifier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleIdentifierFocusLost(evt);
            }
        });
        txtVehicleIdentifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehicleIdentifierKeyReleased(evt);
            }
        });

        lblUniqueID.setText("Unique ID");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload Image");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        txtUniqueID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUniqueIDFocusLost(evt);
            }
        });
        txtUniqueID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUniqueIDKeyReleased(evt);
            }
        });

        jLabel1.setText("Upload Personal Image");

        lblValName.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValName.setForeground(new java.awt.Color(204, 0, 0));

        lblValVeh.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValVeh.setForeground(new java.awt.Color(204, 0, 0));

        lblValDevNum.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValDevNum.setForeground(new java.awt.Color(204, 0, 0));

        lblValLinkedIn.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValLinkedIn.setForeground(new java.awt.Color(204, 0, 0));

        lblValIpAdd.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValIpAdd.setForeground(new java.awt.Color(204, 0, 0));

        lblValUniqueId.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValUniqueId.setForeground(new java.awt.Color(204, 0, 0));

        lblValMed.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValMed.setForeground(new java.awt.Color(204, 0, 0));

        lblValSSN.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValSSN.setForeground(new java.awt.Color(204, 0, 0));

        lblValHealth.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValHealth.setForeground(new java.awt.Color(204, 0, 0));

        lblValBankAcc.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValBankAcc.setForeground(new java.awt.Color(204, 0, 0));

        lblValLic.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValLic.setForeground(new java.awt.Color(204, 0, 0));

        lblValGeo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValGeo.setForeground(new java.awt.Color(204, 0, 0));

        lblValTel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValTel.setForeground(new java.awt.Color(204, 0, 0));

        lblValFax.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValFax.setForeground(new java.awt.Color(204, 0, 0));

        lblValEmail.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblValEmail.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHealthPlanBeneficiaryNumber)
                    .addComponent(lblGeographicData)
                    .addComponent(lblName)
                    .addComponent(lblDOB)
                    .addComponent(lblFaxNumber)
                    .addComponent(lblTelephoneNumber)
                    .addComponent(lblEmail)
                    .addComponent(lblSocialSecurityNumber)
                    .addComponent(lblMedicalRecordNumber)
                    .addComponent(lblGeographicData1)
                    .addComponent(lblCertificatelicensenumber)
                    .addComponent(lblVehicleIdentifier)
                    .addComponent(lblDeviceID)
                    .addComponent(lblLinkedIn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUniqueID)
                        .addComponent(lblIPAdress))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(txtFaxNumber)
                    .addComponent(txtBankAccountNumber)
                    .addComponent(txtEmailAddress)
                    .addComponent(txtCertificateLicenseNumber)
                    .addComponent(txtSocialSecurityNumber)
                    .addComponent(txtMedicalRecordNumber)
                    .addComponent(txtVehicleIdentifier)
                    .addComponent(txtDeviceID)
                    .addComponent(txtGeographicData)
                    .addComponent(txtLinkedIn)
                    .addComponent(txtIPAdress)
                    .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelephoneNumber)
                    .addComponent(txtHealthPlanBeneficiaryNumber)
                    .addComponent(txtUniqueID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValIpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValDevNum, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValLic, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValMed, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValFax, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValTel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValGeo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBankAccountNumber, txtCertificateLicenseNumber, txtDOB, txtDeviceID, txtEmailAddress, txtFaxNumber, txtGeographicData, txtHealthPlanBeneficiaryNumber, txtIPAdress, txtLinkedIn, txtMedicalRecordNumber, txtName, txtSocialSecurityNumber, txtTelephoneNumber, txtVehicleIdentifier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeographicData)
                    .addComponent(txtGeographicData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValGeo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephoneNumber)
                    .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValFax))
                    .addComponent(lblFaxNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialSecurityNumber)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValSSN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecordNumber)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValMed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHealthPlanBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValHealth))
                    .addComponent(lblHealthPlanBeneficiaryNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValBankAcc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblGeographicData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertificatelicensenumber)
                    .addComponent(txtCertificateLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValLic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValVeh))
                    .addComponent(lblVehicleIdentifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDeviceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValDevNum))
                    .addComponent(lblDeviceID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValLinkedIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAdress)
                    .addComponent(txtIPAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValIpAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUniqueID)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnUpload)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValUniqueId)))
                .addGap(29, 29, 29)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int X=0;
        person.setName(txtName.getText());
        person.setGeographicData(txtGeographicData.getText());
        person.setDOB(txtDOB.getDate());
        person.setPhoneNumber(Long.valueOf(txtTelephoneNumber.getText() ));
        person.setFaxNumber(txtFaxNumber.getText());
        person.setEmail(txtEmailAddress.getText());
        person.setSSN(txtSocialSecurityNumber.getText());
        person.setMedicalNumber(txtMedicalRecordNumber.getText());
        person.setHealthPlanNumber(txtHealthPlanBeneficiaryNumber.getText());
        person.setBankAccountNumber(txtBankAccountNumber.getText());
        person.setCertificateNumber(txtCertificateLicenseNumber.getText());
        person.setVehicleID(txtVehicleIdentifier.getText());
        person.setDeviceID(txtDeviceID.getText());
        person.setLinkedIn(txtLinkedIn.getText());
        person.setIPAdress(txtIPAdress.getText());
        person.setUniqueID(txtUniqueID.getText());
       
       JOptionPane.showMessageDialog(this,"Person Profile information is saved.");
              
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser image = new JFileChooser();
        
        image.showOpenDialog(null);
        File selectedFile = image.getSelectedFile();
        //String filename= selectedFile.getAbsolutePath();
        
        person.setImage(selectedFile);           
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtFaxNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumberActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        
        //Validation to check if name is alphabetic
         String checkName=txtName.getText();
      
       Pattern pattern=Pattern.compile("^[a-zA-Z- ]{1,50}$");
       Matcher matchPattern=pattern.matcher(checkName);
           if(!matchPattern.matches())
            {
            JOptionPane.showMessageDialog(this," Please Enter Only Charaters. ");
           }
             
    }//GEN-LAST:event_txtNameFocusLost

    private void txtTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTelephoneNumberActionPerformed

    private void txtTelephoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelephoneNumberFocusLost
        // TODO add your handling code here:
//        String checkNumber=txtTelephoneNumber.getText();
//             
//        Pattern pattern=Pattern.compile("^[0-9]{10}$");
//        Matcher matchPattern=pattern.matcher(checkNumber);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Correct Phone Number. ");
//            }
    }//GEN-LAST:event_txtTelephoneNumberFocusLost

    private void txtGeographicDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGeographicDataFocusLost
        // TODO add your handling code here:
        
//         String checkAddress=txtGeographicData.getText();
//              
//        Pattern pattern=Pattern.compile("^[a-zA-Z0-9-, ]{2,50}$");
//
//        Matcher matchPattern=pattern.matcher(checkAddress);
//            if(!matchPattern.matches())
//            {
            //JOptionPane.showMessageDialog(this," Please Enter Valid Geographic Data. ");
            //}
    }//GEN-LAST:event_txtGeographicDataFocusLost

    private void txtFaxNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFaxNumberFocusLost
        // TODO add your handling code here:
//         String checkFaxNumber=txtFaxNumber.getText();
//       
//        Pattern pattern=Pattern.compile("^[0-9]{8}$");
//
//        Matcher matchPattern=pattern.matcher(checkFaxNumber);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Fax Number. ");
//            }
    }//GEN-LAST:event_txtFaxNumberFocusLost

    private void txtEmailAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailAddressFocusLost
        // TODO add your handling code here:
        String checkEmailAddress=txtEmailAddress.getText();
      
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$");
        Matcher matchPattern=pattern.matcher(checkEmailAddress);
            if(!matchPattern.matches())
            {
            JOptionPane.showMessageDialog(this," Please Enter Valid Email Address. ");
            }
    }//GEN-LAST:event_txtEmailAddressFocusLost

    private void txtSocialSecurityNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSocialSecurityNumberFocusLost
        // TODO add your handling code here:
//               
//        String checkSSN=txtSocialSecurityNumber.getText();
//       
//        Pattern pattern=Pattern.compile("^[0-9]{9}$");
//
//        Matcher matchPattern=pattern.matcher(checkSSN);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Social Security Number. ");
//            }
    }//GEN-LAST:event_txtSocialSecurityNumberFocusLost

    private void txtHealthPlanBeneficiaryNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHealthPlanBeneficiaryNumberFocusLost
        // TODO add your handling code here:
        
//        String checkHealthPlanBeneficiaryNumber=txtHealthPlanBeneficiaryNumber.getText();
//       
//        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]{10}$");
//
//        Matcher matchPattern=pattern.matcher(checkHealthPlanBeneficiaryNumber);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Health Plan Beneficinary Number. ");
//            }
    }//GEN-LAST:event_txtHealthPlanBeneficiaryNumberFocusLost

    private void txtBankAccountNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBankAccountNumberFocusLost
        // TODO add your handling code here:
//        String checkBankAccountNumber=txtBankAccountNumber.getText();
//       
//        Pattern pattern=Pattern.compile("^[0-9]{12}$");
//
//        Matcher matchPattern=pattern.matcher(checkBankAccountNumber);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Bank Account Number. ");
//            }
    }//GEN-LAST:event_txtBankAccountNumberFocusLost

    private void txtCertificateLicenseNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCertificateLicenseNumberFocusLost
        // TODO add your handling code here:
        
//        String checkCertificateLicenseNumber=txtCertificateLicenseNumber.getText();
//       
//        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]{5,10}$");
//
//        Matcher matchPattern=pattern.matcher(checkCertificateLicenseNumber);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Certificate License Number. ");
//            }
    }//GEN-LAST:event_txtCertificateLicenseNumberFocusLost

    private void txtVehicleIdentifierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierFocusLost
        // TODO add your handling code here:
//         String checkVehicleIdentifierNumber=txtVehicleIdentifier.getText();
//       
//        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]{5,10}$");
//
//        Matcher matchPattern=pattern.matcher(checkVehicleIdentifierNumber);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Vehicle Identifier Number. ");
//            }
    }//GEN-LAST:event_txtVehicleIdentifierFocusLost

    private void txtDeviceIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIDFocusLost
        // TODO add your handling code here:
        
                
//                String checkDeviceIDNumber=txtDeviceID.getText();
//       
//        Pattern pattern=Pattern.compile("^[0-9]{4}$");
//
//        Matcher matchPattern=pattern.matcher(checkDeviceIDNumber);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Device Identifier Number. ");
//            }
    }//GEN-LAST:event_txtDeviceIDFocusLost

    private void txtLinkedInFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkedInFocusLost
        // TODO add your handling code here:
        
//          String checkLinkedIn=txtLinkedIn.getText();
//       
//        Pattern pattern=Pattern.compile("^[a-zA-Z- ]{1,50}$");
//
//        Matcher matchPattern=pattern.matcher(checkLinkedIn);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid LinkedIn. ");
//            }
    }//GEN-LAST:event_txtLinkedInFocusLost

    private void txtIPAdressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIPAdressFocusLost
        // TODO add your handling code here:
        String checkIPAdress=txtIPAdress.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{0,3}.[0-9]{0,3}.[0-9]{0,3}.[0-9]{0,3}$");

        Matcher matchPattern=pattern.matcher(checkIPAdress);
            if(!matchPattern.matches())
            {
            JOptionPane.showMessageDialog(this," Please Enter Valid IP Address. ");
            }
    }//GEN-LAST:event_txtIPAdressFocusLost

    private void txtUniqueIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUniqueIDFocusLost
        // TODO add your handling code here:
//        String checkUniqueID=txtUniqueID.getText();
//       
//        Pattern pattern=Pattern.compile("^[0-9]{15}$");
//
//        Matcher matchPattern=pattern.matcher(checkUniqueID);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Unique ID. ");
//            }
    }//GEN-LAST:event_txtUniqueIDFocusLost

    private void txtMedicalRecordNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberFocusLost
        // TODO add your handling code here:
//        String checkMedicalRecordNumber=txtMedicalRecordNumber.getText();
//       
//        Pattern pattern=Pattern.compile("^[0-9]{5}$");
//
//        Matcher matchPattern=pattern.matcher(checkMedicalRecordNumber);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Medical Record Number. ");
//            }
    }//GEN-LAST:event_txtMedicalRecordNumberFocusLost

    private void txtGeographicDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeographicDataKeyReleased
        // TODO add your handling code here:
         String checkAddress=txtGeographicData.getText();
              
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9-, ]{1,50}$");

        Matcher matchPattern=pattern.matcher(checkAddress);
            if(!matchPattern.matches())
            {
                lblValGeo.setText(" Please Enter Valid Geographic Data.");
            
            }
            else{
                lblValGeo.setText(null);
            }
                   
    }//GEN-LAST:event_txtGeographicDataKeyReleased

    private void txtTelephoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneNumberKeyReleased
        // TODO add your handling code here:
       
         String checkNumber=txtTelephoneNumber.getText();
             
        Pattern pattern=Pattern.compile("^[0-9]{1,10}$");
        Matcher matchPattern=pattern.matcher(checkNumber);
            if(!matchPattern.matches())
            {
                lblValTel.setText(" Please Enter Correct Phone Number. ");
            
            }
            else
            {
               lblValTel.setText(null); 
            }
    }//GEN-LAST:event_txtTelephoneNumberKeyReleased

    private void txtFaxNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumberKeyReleased
        // TODO add your handling code here:
        String checkFaxNumber=txtFaxNumber.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,8}$");

        Matcher matchPattern=pattern.matcher(checkFaxNumber);
            if(!matchPattern.matches())
            {
                lblValFax.setText(" Please Enter Valid Fax Number. ");
         
            }
            else{
                lblValFax.setText(null);
            }
                  
    }//GEN-LAST:event_txtFaxNumberKeyReleased

    private void txtEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyReleased
        // TODO add your handling code here:
//        String checkEmailAddress=txtEmailAddress.getText();
//       
//        Pattern pattern=Pattern.compile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$");
//        Matcher matchPattern=pattern.matcher(checkEmailAddress);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid Email Address. ");
//            }
    }//GEN-LAST:event_txtEmailAddressKeyReleased

    private void txtSocialSecurityNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSocialSecurityNumberKeyReleased
        // TODO add your handling code here:
               
        String checkSSN=txtSocialSecurityNumber.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,9}$");

        Matcher matchPattern=pattern.matcher(checkSSN);
            if(!matchPattern.matches())
            {
                lblValSSN.setText(" Please Enter Valid Social Security Number. ");
           
            }
            else
            {
                lblValSSN.setText(null);
            }
    }//GEN-LAST:event_txtSocialSecurityNumberKeyReleased

    private void txtMedicalRecordNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberKeyReleased
        // TODO add your handling code here:
        String checkMedicalRecordNumber=txtMedicalRecordNumber.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,5}$");

        Matcher matchPattern=pattern.matcher(checkMedicalRecordNumber);
            if(!matchPattern.matches())
            {
                lblValMed.setText(" Please Enter Valid Medical Record Number. ");
            
            }
            else
            {
                lblValMed.setText(null);
            }
    }//GEN-LAST:event_txtMedicalRecordNumberKeyReleased

    private void txtHealthPlanBeneficiaryNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHealthPlanBeneficiaryNumberKeyReleased
        // TODO add your handling code here:
        String checkHealthPlanBeneficiaryNumber=txtHealthPlanBeneficiaryNumber.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]{1,10}$");

        Matcher matchPattern=pattern.matcher(checkHealthPlanBeneficiaryNumber);
            if(!matchPattern.matches())
            {
                lblValHealth.setText("Please Enter Valid Health Plan Beneficinary Number." );
            
            }
            else{
                lblValHealth.setText(null);
            }
        
    }//GEN-LAST:event_txtHealthPlanBeneficiaryNumberKeyReleased

    private void txtBankAccountNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankAccountNumberKeyReleased
        // TODO add your handling code here:
        String checkBankAccountNumber=txtBankAccountNumber.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,12}$");

        Matcher matchPattern=pattern.matcher(checkBankAccountNumber);
            if(!matchPattern.matches())
            {
            JOptionPane.showMessageDialog(this," Please Enter Valid Bank Account Number. ");
            }
    }//GEN-LAST:event_txtBankAccountNumberKeyReleased

    private void txtCertificateLicenseNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCertificateLicenseNumberKeyReleased
        // TODO add your handling code here:
        
        String checkCertificateLicenseNumber=txtCertificateLicenseNumber.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]{1,10}$");

        Matcher matchPattern=pattern.matcher(checkCertificateLicenseNumber);
            if(!matchPattern.matches())
            {
                lblValLic.setText(" Please Enter Valid Certificate License Number. ");
            
            }
            else
            {
                 lblValLic.setText(null);
            }
    }//GEN-LAST:event_txtCertificateLicenseNumberKeyReleased

    private void txtVehicleIdentifierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierKeyReleased
        // TODO add your handling code here:
         String checkVehicleIdentifierNumber=txtVehicleIdentifier.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]{1,10}$");

        Matcher matchPattern=pattern.matcher(checkVehicleIdentifierNumber);
            if(!matchPattern.matches())
            {
                lblValVeh.setText("Please Enter Valid Vehicle Identifier Number.");
//            JOptionPane.showMessageDialog(this," Please Enter Valid Vehicle Identifier Number. ");
            }
            else
            {
            lblValVeh.setText(null);
            }
    }//GEN-LAST:event_txtVehicleIdentifierKeyReleased

    private void txtDeviceIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeviceIDKeyReleased
        // TODO add your handling code here:
        String checkDeviceIDNumber=txtDeviceID.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,4}$");

        Matcher matchPattern=pattern.matcher(checkDeviceIDNumber);
            if(!matchPattern.matches())
            {
                lblValDevNum.setText("Please Enter Valid Device Identifier Number.");
            
            }
            else
            {
                lblValDevNum.setText(null);
            }
    }//GEN-LAST:event_txtDeviceIDKeyReleased

    private void txtLinkedInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedInKeyReleased
        // TODO add your handling code here:
        String checkLinkedIn=txtLinkedIn.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z- ]{1,50}$");

        Matcher matchPattern=pattern.matcher(checkLinkedIn);
            if(!matchPattern.matches())
            {
                lblValLinkedIn.setText("Please Enter Valid LinkedIn.");
           
            }
            else{
                lblValLinkedIn.setText(null);
            }
    }//GEN-LAST:event_txtLinkedInKeyReleased

    private void txtIPAdressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPAdressKeyReleased
        // TODO add your handling code here:
//        String checkIPAdress=txtIPAdress.getText();
//       
//        Pattern pattern=Pattern.compile("^[0-9]{0,3}.[0-9]{0,3}.[0-9]{0,3}.[0-9]{0,3}$");
//
//        Matcher matchPattern=pattern.matcher(checkIPAdress);
//            if(!matchPattern.matches())
//            {
//            JOptionPane.showMessageDialog(this," Please Enter Valid IP Address. ");
//            }
    }//GEN-LAST:event_txtIPAdressKeyReleased

    private void txtUniqueIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUniqueIDKeyReleased
        // TODO add your handling code here:
         String checkUniqueID=txtUniqueID.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,15}$");

        Matcher matchPattern=pattern.matcher(checkUniqueID);
            if(!matchPattern.matches())
            {
                lblValUniqueId.setText("Please Enter Valid Unique ID.");
            
            }
            else{
                 lblValUniqueId.setText(null);
            }
              
    }//GEN-LAST:event_txtUniqueIDKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        String checkName=txtName.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z]{1,50}$");

        Matcher matchPattern=pattern.matcher(checkName);
            if(!matchPattern.matches())
            {
                lblValName.setText("Please enter correct name.");
            }
            else
            {
                lblValName.setText(null);
            }
    }//GEN-LAST:event_txtNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCertificatelicensenumber;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceID;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblGeographicData;
    private javax.swing.JLabel lblGeographicData1;
    private javax.swing.JLabel lblHealthPlanBeneficiaryNumber;
    private javax.swing.JLabel lblIPAdress;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSocialSecurityNumber;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblValBankAcc;
    private javax.swing.JLabel lblValDevNum;
    private javax.swing.JLabel lblValEmail;
    private javax.swing.JLabel lblValFax;
    private javax.swing.JLabel lblValGeo;
    private javax.swing.JLabel lblValHealth;
    private javax.swing.JLabel lblValIpAdd;
    private javax.swing.JLabel lblValLic;
    private javax.swing.JLabel lblValLinkedIn;
    private javax.swing.JLabel lblValMed;
    private javax.swing.JLabel lblValName;
    private javax.swing.JLabel lblValSSN;
    private javax.swing.JLabel lblValTel;
    private javax.swing.JLabel lblValUniqueId;
    private javax.swing.JLabel lblValVeh;
    private javax.swing.JLabel lblVehicleIdentifier;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtCertificateLicenseNumber;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtDeviceID;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtGeographicData;
    private javax.swing.JTextField txtHealthPlanBeneficiaryNumber;
    private javax.swing.JTextField txtIPAdress;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtUniqueID;
    private javax.swing.JTextField txtVehicleIdentifier;
    // End of variables declaration//GEN-END:variables
        
}
