/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Car;
import model.CarListHistory;

/**
 *
 * @author deepalikasture
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    CarListHistory carList;
    public CreateJPanel(CarListHistory carList) {
        initComponents();
        this.carList=carList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCar = new javax.swing.JLabel();
        lblCarName = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        lblManufacterdYear = new javax.swing.JLabel();
        txtManufacterdYear = new javax.swing.JTextField();
        lblNumberOfSeats = new javax.swing.JLabel();
        txtNumberOfSeats = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        lblisExpired = new javax.swing.JLabel();
        chkAvailability = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        chkIsExpired = new javax.swing.JCheckBox();
        lblValName = new javax.swing.JLabel();
        lblValModelNumber = new javax.swing.JLabel();
        lblValManufacturedYear = new javax.swing.JLabel();
        lblValNumberOfSeats = new javax.swing.JLabel();
        lblValSerialNumber = new javax.swing.JLabel();
        lblValCity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        lblAddCar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblAddCar.setText("                                                   Add Car");

        lblCarName.setText("Car Name");

        txtCarName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCarNameKeyReleased(evt);
            }
        });

        jLabel1.setText("Model Number");

        txtModelNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModelNumberKeyReleased(evt);
            }
        });

        lblManufacterdYear.setText("Manufacterd Year");

        txtManufacterdYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtManufacterdYearKeyReleased(evt);
            }
        });

        lblNumberOfSeats.setText("Number of Seats");

        txtNumberOfSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumberOfSeatsKeyReleased(evt);
            }
        });

        lblSerialNumber.setText("Serial Number");

        txtSerialNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerialNumberKeyReleased(evt);
            }
        });

        lblCity.setText("City");

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });

        lblAvailability.setText("Availability");

        lblisExpired.setText("Expired?");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblValName.setForeground(new java.awt.Color(153, 51, 0));

        lblValModelNumber.setForeground(new java.awt.Color(153, 51, 0));

        lblValManufacturedYear.setForeground(new java.awt.Color(153, 0, 0));

        lblValNumberOfSeats.setForeground(new java.awt.Color(153, 0, 0));

        lblValSerialNumber.setForeground(new java.awt.Color(204, 51, 0));

        lblValCity.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManufacterdYear)
                            .addComponent(lblCarName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumberOfSeats)
                            .addComponent(lblSerialNumber)
                            .addComponent(lblCity)
                            .addComponent(lblAvailability)
                            .addComponent(lblisExpired))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(txtModelNumber)
                    .addComponent(chkAvailability)
                    .addComponent(chkIsExpired)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCarName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtManufacterdYear)
                            .addComponent(txtNumberOfSeats)
                            .addComponent(txtSerialNumber)
                            .addComponent(txtCity))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValCity)
                            .addComponent(lblValSerialNumber)
                            .addComponent(lblValNumberOfSeats)
                            .addComponent(lblValManufacturedYear)
                            .addComponent(lblValModelNumber)
                            .addComponent(lblValName))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCarName, txtCity, txtManufacterdYear, txtModelNumber, txtNumberOfSeats, txtSerialNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAddCar)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValModelNumber))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacterdYear)
                    .addComponent(txtManufacterdYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValManufacturedYear))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfSeats)
                    .addComponent(txtNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValNumberOfSeats))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNumber)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValSerialNumber)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCity))
                    .addComponent(lblValCity))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvailability)
                    .addComponent(chkAvailability))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblisExpired)
                    .addComponent(chkIsExpired))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCarName, txtCity, txtManufacterdYear, txtModelNumber, txtNumberOfSeats, txtSerialNumber});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        int manufacturingYear=Integer.parseInt(txtManufacterdYear.getText());
        long seatCount=Long.parseLong(txtNumberOfSeats.getText());
        String modelNumber = txtModelNumber.getText();
        String city = txtCity.getText();
        String carName = txtCarName.getText();
       
       
        String serialNumber=txtSerialNumber.getText();
        Boolean isAvailable =Boolean.FALSE;
        Boolean isExpired= Boolean.FALSE;
                if(chkAvailability.isSelected())
                {
                     isAvailable=Boolean.TRUE;
                }
                else
                {
                    isAvailable =Boolean.FALSE;
                }
                
                if(chkIsExpired.isSelected())
                {
                     isExpired=Boolean.TRUE;
                }
                else
                {
                    isExpired =Boolean.FALSE;
                }
        
        Car c= carList.addNewCar();
        
        c.setName(carName);
        c.setCity(city);
       
        c.setManufacturedYear(String.valueOf(manufacturingYear));
        c.setNumberOfSeats(seatCount);
        c.setSerialNumber(serialNumber);
        c.setIsAvailable(isAvailable);
        c.setIsExpired(isExpired);
        c.setModelNumber(modelNumber);
        
        JOptionPane.showMessageDialog(this, "New Car Added!");
        
        txtCarName.setText("");
        txtNumberOfSeats.setText("");
        txtModelNumber.setText("");
        txtCity.setText("");
        txtManufacterdYear.setText("");
        txtSerialNumber.setText("");
        chkAvailability.setSelected(false);
        chkIsExpired.setSelected(false);
          SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
    Date date = new Date();  
    carList.setLastUpdatedDate(date);
            
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCarNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarNameKeyReleased
        // TODO add your handling code here:
         String checkName=txtCarName.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z]{1,50}$");

        Matcher matchPattern=pattern.matcher(checkName);
            if(!matchPattern.matches())
            {
                lblValName.setText("Please enter correct name.");
            }
            else
            {
                lblValName.setText(null);
            }
    }//GEN-LAST:event_txtCarNameKeyReleased

    private void txtModelNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelNumberKeyReleased
        // TODO add your handling code here:
        
         String checkModelNumber=txtModelNumber.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]{1,5}$");

        Matcher matchPattern=pattern.matcher(checkModelNumber);
            if(!matchPattern.matches())
            {
                lblValModelNumber.setText("Please Enter Valid Model Number." );
            
            }
            else{
                lblValModelNumber.setText(null);
            }
    }//GEN-LAST:event_txtModelNumberKeyReleased

    private void txtManufacterdYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufacterdYearKeyReleased
        // TODO add your handling code here:
        
        String checkManufacterdYear=txtManufacterdYear.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1,4}$");

        Matcher matchPattern=pattern.matcher(checkManufacterdYear);
            if(!matchPattern.matches())
            {
                lblValManufacturedYear.setText("Please Enter Valid Year." );
            
            }
            else{
                lblValManufacturedYear.setText(null);
            }
    }//GEN-LAST:event_txtManufacterdYearKeyReleased

    private void txtNumberOfSeatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumberOfSeatsKeyReleased
        // TODO add your handling code here:
        
        String checkNumberOfSeats=txtNumberOfSeats.getText();
       
        Pattern pattern=Pattern.compile("^[0-9]{1}$");

        Matcher matchPattern=pattern.matcher(checkNumberOfSeats);
            if(!matchPattern.matches())
            {
                lblValNumberOfSeats.setText("Please Enter Valid Number." );
            
            }
            else{
                lblValNumberOfSeats.setText(null);
            }
    }//GEN-LAST:event_txtNumberOfSeatsKeyReleased

    private void txtSerialNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumberKeyReleased
        // TODO add your handling code here:
        String checkSerialNumber=txtSerialNumber.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z0-9]{1,6}$");

        Matcher matchPattern=pattern.matcher(checkSerialNumber);
            if(!matchPattern.matches())
            {
                lblValSerialNumber.setText("Please Enter Valid Serial Number." );
            
            }
            else{
                lblValSerialNumber.setText(null);
            }
    }//GEN-LAST:event_txtSerialNumberKeyReleased

    private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
        // TODO add your handling code here:
        
         String checkCity=txtCity.getText();
       
        Pattern pattern=Pattern.compile("^[a-zA-Z]{1,50}$");

        Matcher matchPattern=pattern.matcher(checkCity);
            if(!matchPattern.matches())
            {
                lblValCity.setText("Please enter only letters");
            }
            else
            {
                lblValCity.setText(null);
            }
    }//GEN-LAST:event_txtCityKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkAvailability;
    private javax.swing.JCheckBox chkIsExpired;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddCar;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManufacterdYear;
    private javax.swing.JLabel lblNumberOfSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblValCity;
    private javax.swing.JLabel lblValManufacturedYear;
    private javax.swing.JLabel lblValModelNumber;
    private javax.swing.JLabel lblValName;
    private javax.swing.JLabel lblValNumberOfSeats;
    private javax.swing.JLabel lblValSerialNumber;
    private javax.swing.JLabel lblisExpired;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacterdYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtNumberOfSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
