/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarListHistory;

/**
 *
 * @author deepalikasture
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    CarListHistory carList;
    public ViewJPanel(CarListHistory carList) {
        initComponents();
        this.carList= carList;

        populateTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarList = new javax.swing.JTable();
        chkIsExpired = new javax.swing.JCheckBox();
        lblCarName = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        lblManufacterdYear = new javax.swing.JLabel();
        txtManufacterdYear = new javax.swing.JTextField();
        lblisExpired = new javax.swing.JLabel();
        lblNumberOfSeats = new javax.swing.JLabel();
        txtNumberOfSeats = new javax.swing.JTextField();
        chkAvailability = new javax.swing.JCheckBox();
        lblSerialNumber = new javax.swing.JLabel();
        btnUpadte = new javax.swing.JButton();
        txtSerialNumber = new javax.swing.JTextField();
        txtLastUpdatedCatlogDate = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnLastUpdatedCatlog = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        lblAddCar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblAddCar.setText("                                                   View Car Details");

        tblCarList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Name", "Model Number", "Serial Number", "City", "Manufactered Year", "Number of Seats", "isAvailable", "Is Expired?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarList);

        lblCarName.setText("Car Name");

        lblCity.setText("City");

        jLabel1.setText("Model Number");

        lblAvailability.setText("Availability");

        lblManufacterdYear.setText("Manufacterd Year");

        lblisExpired.setText("Expired?");

        lblNumberOfSeats.setText("Number of Seats");

        lblSerialNumber.setText("Serial Number");

        btnUpadte.setText("Update");
        btnUpadte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpadteActionPerformed(evt);
            }
        });

        txtLastUpdatedCatlogDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastUpdatedCatlogDateActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnLastUpdatedCatlog.setText("Last Updated Catlog");
        btnLastUpdatedCatlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastUpdatedCatlogActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Edit Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(274, 274, 274))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(btnLastUpdatedCatlog)
                            .addGap(18, 18, 18)
                            .addComponent(txtLastUpdatedCatlogDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(167, 167, 167)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblManufacterdYear)
                                            .addComponent(lblCarName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblNumberOfSeats)
                                                .addComponent(lblSerialNumber)
                                                .addComponent(lblCity)
                                                .addComponent(lblAvailability)
                                                .addComponent(lblisExpired))))
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtManufacterdYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpadte)
                                        .addComponent(chkAvailability)
                                        .addComponent(chkIsExpired)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCarName, txtCity, txtManufacterdYear, txtModelNumber, txtNumberOfSeats, txtSerialNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAddCar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLastUpdatedCatlog)
                    .addComponent(txtLastUpdatedCatlogDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacterdYear)
                    .addComponent(txtManufacterdYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfSeats)
                    .addComponent(txtNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvailability)
                    .addComponent(chkAvailability))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblisExpired)
                    .addComponent(chkIsExpired))
                .addGap(18, 18, 18)
                .addComponent(btnUpadte)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpadteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpadteActionPerformed
        // TODO add your handling code here:

         int selectedRowIndex=tblCarList.getSelectedRow();
         if(selectedRowIndex<0){
             JOptionPane.showMessageDialog(this, "Please select a row to update");
         }
        DefaultTableModel model = (DefaultTableModel) tblCarList.getModel();
        Car car=(Car) model.getValueAt(selectedRowIndex,0);
       car.setName(txtCarName.getText());
       car.setManufacturedYear(txtManufacterdYear.getText());
      
       car.setCity(txtCity.getText());
       car.setNumberOfSeats(Integer.parseInt(txtNumberOfSeats.getText()));
       car.setSerialNumber(txtSerialNumber.getText() );
       car.setModelNumber(txtModelNumber.getText());
       car.setIsAvailable(chkAvailability.isSelected());
       car.setIsExpired(chkIsExpired.isSelected());
       JOptionPane.showMessageDialog(this, "Data is successfully updated.");
     SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
    Date date = new Date();  
    carList.setLastUpdatedDate(date);
            txtLastUpdatedCatlogDate.setText(formatter.format(carList.getLastUpdatedDate()));
    }//GEN-LAST:event_btnUpadteActionPerformed

    private void txtLastUpdatedCatlogDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastUpdatedCatlogDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastUpdatedCatlogDateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         int selectedRowId=tblCarList.getSelectedRow();
         if(selectedRowId<0){
             JOptionPane.showMessageDialog(this, "Please select a row to edit");
         }
        DefaultTableModel model = (DefaultTableModel) tblCarList.getModel();

        txtCarName.setText(String.valueOf(model.getValueAt(selectedRowId, 0)));
       
        txtManufacterdYear.setText(String.valueOf(model.getValueAt(selectedRowId, 4)));
        txtCity.setText(String.valueOf(model.getValueAt(selectedRowId, 3)));
        txtModelNumber.setText(String.valueOf(model.getValueAt(selectedRowId, 1)));
        txtSerialNumber.setText(String.valueOf(model.getValueAt(selectedRowId, 2)));
        chkAvailability.setSelected(Boolean.valueOf(model.getValueAt(selectedRowId, 6).toString()));
        chkIsExpired.setSelected(Boolean.valueOf(model.getValueAt(selectedRowId, 7).toString()));
        txtNumberOfSeats.setText(String.valueOf(String.valueOf(model.getValueAt(selectedRowId, 5))));

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
         int selectedRowIndex=tblCarList.getSelectedRow();
         if(selectedRowIndex<0){
             JOptionPane.showMessageDialog(this, "Please select a row to delete");
         }
        DefaultTableModel model = (DefaultTableModel) tblCarList.getModel();
        System.out.println(model.getValueAt(selectedRowIndex,0));
        Car selectedCar=(Car) model.getValueAt(selectedRowIndex,0);
                System.out.println(selectedCar);

        carList.deleteCar(selectedCar);
        JOptionPane.showMessageDialog(this, "Car entry deleted");
        populateTable();
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
    Date date = new Date();  
    carList.setLastUpdatedDate(date);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLastUpdatedCatlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastUpdatedCatlogActionPerformed
        // TODO add your handling code here:
//         if(carList.getLastUpdatedDate().equals(null)){
//        txtLastUpdatedCatlogDate.setText(carList.getLastUpdatedDate().toString());
//        }
//        else
//        {
//           txtLastUpdatedCatlogDate.setText(""); 
//        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        txtLastUpdatedCatlogDate.setText(dateFormat.format(carList.getLastUpdatedDate()));
    }//GEN-LAST:event_btnLastUpdatedCatlogActionPerformed
 
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCarList.getModel();
        model.setRowCount(0);
        for(Car car: carList.getCarList()){
        Object[] row=new Object[10];
        row[0]=car;
        row[1]=car.getModelNumber();
        row[2]=car.getSerialNumber();
        row[3]=car.getCity();
        row[4]=car.getManufacturedYear();
        row[5]=car.getNumberOfSeats();
        row[6]=car.getIsAvailable();
        row[7]=car.getIsExpired();
        

    model.addRow(row);
    
        }
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLastUpdatedCatlog;
    private javax.swing.JButton btnUpadte;
    private javax.swing.JCheckBox chkAvailability;
    private javax.swing.JCheckBox chkIsExpired;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddCar;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManufacterdYear;
    private javax.swing.JLabel lblNumberOfSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblisExpired;
    private javax.swing.JTable tblCarList;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtLastUpdatedCatlogDate;
    private javax.swing.JTextField txtManufacterdYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtNumberOfSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
